Week 2

Step 1: Load in Sold data

In [23]:
import pandas as pd
import matplotlib.pyplot as plt

Step 2: Dataset Understanding

In [6]:
sold_data = pd.read_csv('sold.csv')

/var/folders/mf/9m6y4nlx41z0kjyljz4sn3tc0000gn/T/ipykernel_3191/343568724.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: WaterfrontYN, 3: OriginatingSystemName, 4: OriginatingSystemSubName, 5: ListAgentEmail, 6: latfilled, 7: lonfilled, 8: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  sold_data = pd.read_csv('sold.csv')

Row count before Residential Filter (includes all PropertyType's): 591191

Row count AFTER Residential Filter: 397261

In [7]:
sold_data.shape

(397261, 84)

Missing Value Analysis

In [11]:
missing_counts = sold_data.isna().sum()

missing_pct = (missing_counts / len(sold_data)) * 100

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_pct": missing_pct
})

missing_summary["90pct_missing"] = missing_summary["missing_pct"] > 90

missing_summary = missing_summary.sort_values(by="missing_pct", ascending=False)

missing_summary.head(5)

                              missing_count  missing_pct  90pct_missing
CoveredSpaces                        397261        100.0           True
MiddleOrJuniorSchoolDistrict         397261        100.0           True
TaxAnnualAmount                      397261        100.0           True
ElementarySchoolDistrict             397261        100.0           True
TaxYear                              397261        100.0           True

Numeric Distribution Review

In [12]:
cols = [
    "ClosePrice", "ListPrice", "OriginalListPrice",
    "LivingArea", "LotSizeAcres",
    "BedroomsTotal", "BathroomsTotalInteger",
    "DaysOnMarket", "YearBuilt"
]

Summary Statistics

In [32]:
summary_list = []
for col in cols: 
    data = sold_data[col].dropna()
    summary = {
        "column": col,
        "count": len(data),
        "mean": data.mean(),
        "median": data.median(),
        "std": data.std(),
        "min": data.min(),
        "max": data.max(),
    }
    
    summary_list.append(summary)
    
summary_df = pd.DataFrame(summary_list)
summary_df.head(5)

,column,count,mean,median,std,min,max
0,ClosePrice,397259,1.186331e+06,820000.0000,5.982138e+06,0.0,9.895000e+08
1,ListPrice,397261,1.138634e+06,815000.0000,1.353851e+06,525.0,1.375000e+08
2,OriginalListPrice,396547,1.224839e+06,825000.0000,6.782589e+06,0.0,1.390000e+09
3,LivingArea,397033,1.904379e+03,1641.0000,2.702940e+04,0.0,1.702132e+07
4,LotSizeAcres,365941,6.837618e+01,0.1663,1.633325e+04,0.0,7.810698e+06

Percentile Statistics

In [37]:
percentiles = data.quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])
column_percentile = []
outlier_dict = {}

for col in cols:
    data = sold_data[col].dropna()
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    
    outlier_dict[col] = outliers

    percentages = {
        "column": col,
        "1%": percentiles.loc[0.01],
        "99%": percentiles.loc[0.99],
        "outlier_count": len(outliers)
    }
    
    column_percentile.append(percentages)
    column_distribution = pd.DataFrame(column_percentile)
    
column_distribution.head()

              column      1%     99%  outlier_count
0         ClosePrice  1912.0  2025.0          29383
1          ListPrice  1912.0  2025.0          29553
2  OriginalListPrice  1912.0  2025.0          30839
3         LivingArea  1912.0  2025.0          17527
4       LotSizeAcres  1912.0  2025.0          56935